### ISSUE TITLE
Isabelle Week 1 Review Ticket: Lists and Loops

### ISSUE THREAD

**Issue by isabelle926** [isabelle926/isabelle_csptri3_individual#2]
# Score: 2.75/3
## Individual GitHub pages (3 points)
GitHub page for Test Prep study, requiring 5.3, 5.4 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders](https://cspcoders.nighthawkcodingsociety.com/)).
- [ ] One Check 5.3
- [ ] One Check 5.4

GitHub page that documents key learnings and code snippets using GitHub and replit.
InfoDB lists
- [ ] One Check for New Data, minimum of 4 items

InfoDB loops
- [ ] One Check For Loop running and sensible output
- [ ] One Check While Loop running and sensible output
- [ ] One Check Recursion running and sensible output

Fibonacci - (For Fibonacci(n) print complete list 0 - n and not just the nth term)
- [ ] Four checks: Algorithm, code with comments, Prints result, Prints Complete List,
- [ ] One check: comments and documentation throughout

**Comment by Dylanluo05** [comment]
> ## Individual GitHub pages (Overall Score: 2.75/3)
> GitHub page for Test Prep study, requiring 5.3, 5.4 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders](https://cspcoders.nighthawkcodingsociety.com/)).
> 
> * [x]  One Check 5.3
> * [x]  One Check 5.4
> 
> GitHub page that documents key learnings and code snippets using GitHub and replit. InfoDB lists
> 
> * []  One Check for New Data, minimum of 4 items
> 
> InfoDB loops
> 
> * [x]  One Check For Loop running and sensible output
> * [x]  One Check While Loop running and sensible output
> * [x]  One Check Recursion running and sensible output
> 
> Fibonacci - (For Fibonacci(n) print complete list 0 - n and not just the nth term)
> 
> * [x]  Four checks: Algorithm, code with comments, Prints result, Prints Complete List,
> * [x]  One check: comments and documentation throughout

Feedback: All of the code requirements were met. The for loop, while loop, recursive loop, and Fibonacci sequence were all present. GitHub notes were also completed. The only thing that was missing was the key learnings and code snippets, so 0.25 points will be taken off.
