### ISSUE TITLE
Isabelle Week 2 Review Ticket Classy Functions

### ISSUE THREAD

**Issue by isabelle926** [isabelle926/isabelle_csptri3_individual#3]
# Total Score: 6/5 
### Grader: Dylan Luo

Individual GitHub pages (3 points)

- [x] GitHub page that documents key learnings and code snippets using GitHub and replit (See Challenges at the bottom of  [TT2 (Links to an external site.)](https://github.com/nighthawkcoders/nighthawk_csp/wiki/Tri-3-TT2-Python-Classes) for details)

- [x] Organize files, directories and menus for the first 3 weeks. 

- [x] Write Factorial function using classes, providing implementation of call.

- [x] Select your own Math function. Write it in Imperative and OOP form. 

- [x] Extra Credit.  Write Palindrome function using classes, must provide implementation of call.  Must indicate where error occurs on front and back comparison.

**Comment by Dylanluo05** [comment]
> ### Individual GitHub pages (Overall Score: 4/3 Points) ###
> 
> * [x]  GitHub page that documents key learnings and code snippets using GitHub and replit (See Challenges at the bottom of  [TT2 (Links to an external site.)](https://github.com/nighthawkcoders/nighthawk_csp/wiki/Tri-3-TT2-Python-Classes) for details)
> * [x]  Organize files, directories and menus for the first 3 weeks.
> * [x]  Write Factorial function using classes, providing implementation of call.
> * [x]  Select your own Math function. Write it in Imperative and OOP form.
> * [x]  Extra Credit.  Write Palindrome function using classes, must provide implementation of call.  Must indicate where error occurs on front and back comparison.

All of the requirements were met. All of the files and directories were organized, and the Factorial and Math functions were working properly. The extra credit Palindrome function was functioning properly too.
