### ISSUE TITLE
Isabelle Week 4 Review Ticket

### ISSUE THREAD

**Issue by isabelle926** [isabelle926/isabelle_csptri3_individual#5]
CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)

    CB Create Task Coding requirements documented
    Runtime of Code(with comments) on Replit/Intellij

**Comment by Dylanluo05** [comment]
> ### Total Overall Grade: 2/2 Points (Grader: Dylan Luo) ###
> CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (Individual)
> ```
> - [x] CB Create Task Coding requirements documented
> - [x] Runtime of Code(with comments) on Replit/Intellij
> ```

Isabelle's total overall grade for this assignment is 2/2 points. Her Create Task Coding requirements were documented in detail, and she had all of the Runtime for her Create Task Coding. Her Rat Simulator is a very fascinating educational program.
