### ISSUE TITLE
Proctored MCQ 1 : Quiz1,Quiz2 Scores

### ISSUE THREAD

**Issue by isabelle926** [isabelle926/isabelle_csptri3_individual#6]
# Score: 5/5
### Study Plan - 4/18 - 4/22
- Monday: Crossover review for last week's assignment, take feedback from crossover partner to fix create task
- Tuesday: Take MCQ 1
- Wednesday: Look over incorrect answers for MCQ 1 and study relevant areas extensively
- Thursday: Take MCQ 2
- Friday: Look over incorrect answers for MCQ 2 and study relevant areas extensively, work on create task written responses

### 4/25-4/29
- Monday: Crossover review
- Tuesday: Take MCQ 3
- Wednesday: Correct MCQ 3 and study relevant areas
- Thursday: work on fun skit
- Friday: deliver fun skit, work on create task

**Comment by isabelle926** [comment]
MCQ 1 Score: 43/50
[Test 1 Corrections](https://github.com/isabelle926/isabelle_csptri3_individual/blob/gh-pages/corrections/test_1.md)
MCQ 2 Score: 47/50
[Test 2 Corrections](https://github.com/isabelle926/isabelle_csptri3_individual/blob/gh-pages/corrections/test_2.md)

**Comment by PrishaB** [comment]
Overall Score: 5/5
- Test corrections are there and through for both Final practice tests
- Study plan is added for previous week and this week and looks pretty thorough
- Create Task and writeup is complete, the video fits the one minute requirement and all requirements for the task appear to be there
- She looks like she'll be prepared for the AP Exam and, if not, she should be able to improve in the next few weeks thanks to her goals and planning
