### ISSUE TITLE
Week 6 Review Ticket

### ISSUE THREAD

**Issue by isabelle926** [isabelle926/isabelle_csptri3_individual#7]
# Score: 4.5/5
### Study Plan:
- Monday: Crossover review
- Tuesday: Take practice test
- Wednesday: Correct practice test
- Thursday: work on create task, get ready for skit
- Friday: deliver skit

Points
- Extra Credit for Acting/Skit/Improv (ASI): 0 to +2 in Seed, Everyone must participate, -1 for not participating.  Teacher interested in evaluation by crossover on how the student did in this activity (0, .5, .75, 1) as team, (-1, .5, .75, 1) as individual. This should be in relation to other ASIs.  Donuts to winning Team.
- MCQ live result > 50%, (1 or 0)
- Ticket(send your own review ticket with score and grader name on the top), GH Pages, Corrections: partial, extreme effort, completed objective (0, .5, .75, 1)

AP Testers
- GH Indi Page, Review Ticket, Crossover graded, Study Plan
- Create Task and Create Task Crossover Review comments (completed by Thu)
- Quiz3 MCQ results and test corrections

Scoring guidelines for crossover graders 4.5/5.0 maximum
- Establish your crossover pair early in the week, they can't be in your ASI activity. You need to know who you are scoring before ASI activity as you will be assisting in evaluations.
- 3 points, use bullets as indicated above, 1 point per sub-bullet
- 1 point, Participation: .20 for classroom presence and participation each day 
- .5 point, Quality of work: grader should be looking at effort toward learning and understanding vs perfunctory bullet chasing (0, .25, .5)
- The last part of grading is providing point total, high points in crossover grading session, positives in work,  and suggestions for future.

**Comment by Dylanluo05** [comment]
The score for this week will be 4.5/5. She had all of the required tangibles, as she had the test corrections, study plan, and Create Performance Task done. Her test corrections were detailed, and she scored 46/50 for the AP Practice MCQ Finals Test 3. Her Create Performance Task was a "rat simulator", where you can select a type of rat to name, feed, play with, and buy toys for. A suggestion for her Create Performance Task is to code a conditional where you can actually win the game.
